# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Big Red Data
tagline:          'Big Data From the Dinosaur Crossing'
description:      "I'm a product manager for Big Data -- hardware and software -- in one of the world's biggest companies.\nSome things here are cross-posts from"
url:              http://dwmclary.github.io

author:
  name:           'Dan McClary'
  url:            https://twitter.com/dan_mcclary

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/dwmclary/
